name = "Spirit Air"
author = "CallMeEcho"
version = "1.0.11"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8c4dece1b62d0d103f3335f050bfc07dce953ea211fcaa686a85486ef5eb57d0"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
