name = "Spirit Air"
author = "CallMeEcho"
version = "1.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f8a34140df872f57498db2ef0cf63edf427c02cda6642fa3e39fbf2d15d1bdfd"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
