name = "Spirit Air"
author = "CallMeEcho"
version = "1.0.11"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "04d85283f7ef94aaa7f612df9e808814e838e81dbab3c4fb8ba0af273af07aab"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
